# Generated by Django 4.0.3 on 2024-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_salesperson_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
