# Generated by Django 4.0.3 on 2024-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_automobilevo_vin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='customer_name',
            field=models.CharField(default='Default Customer', max_length=200),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='vin',
            field=models.CharField(default='Default VIN', max_length=300),
        ),
    ]
