# Generated by Django 4.0.3 on 2024-03-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_appointmentmodel_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technicianmodel'),
        ),
    ]
