# Generated by Django 4.0.3 on 2024-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
