# Generated by Django 4.0.3 on 2024-03-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointmentmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
