# Generated by Django 4.0.3 on 2024-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointmentmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
